version: '3.8'

services:
  wg-peer:
    build: .
    container_name: wg-peer
    privileged: true
    network_mode: host
    healthcheck:             
      test: ["CMD", "ping", "-c", "2", "192.168.1.1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: always
